"""Create reviews table

Revision ID: 172425d7e023
Revises: 2dfe2b63e59c
Create Date: 2026-07-14 10:22:45.670978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172425d7e023'
down_revision = '2dfe2b63e59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actual_outcome', sa.Text(), nullable=False),
    sa.Column('reflection', sa.Text(), nullable=False),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('would_make_same_decision', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
