"""update: created decision model with required fields

Revision ID: 749600205cc2
Revises: 5d7ac3cd0df1
Create Date: 2026-07-12 22:09:08.896150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749600205cc2'
down_revision = '5d7ac3cd0df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('decision_statement', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=True),
    sa.Column('options_considered', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=False),
    sa.Column('expected_outcome', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decisions')
    # ### end Alembic commands ###
